---
# tasks file for test
- name: Update package cache
  become: yes
  apt:
    update_cache: yes

- name: Ensure Nginx is at the latest version
  apt:
    name: nginx
    state: latest

- name: Make sure Nginx is running
  systemd:
    state: started
    name: nginx
    
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'